/**
 * Identifiants des éléments que `app.js` attend dans `index.html`.
 *
 * Cette liste vit dans son propre module pour être vérifiable : un test
 * confronte chaque identifiant au HTML réel, ce qui attrape la faute la plus
 * banale d'une application web — un `id` renommé d'un côté seulement, qui ne
 * produit qu'une erreur `null` à l'exécution.
 */

export const ELEMENT_IDS = Object.freeze([
  'stale-style',
  'count',
  'collection-name',
  'add-form',
  'url-input',
  'add-error',
  'search',
  'select-all',
  'select-none',
  'shortener',
  'shorten',
  'shorten-clear',
  'shorten-status',
  'qr-target',
  'target-hint',
  'date-mode',
  'date-hint',
  'list',
  'empty',
  'export-xlsx',
  'export-csv',
  'export-md',
  'export-json',
  'import',
  'import-file',
  'clear',
  'preset',
  'sheet-qr',
  'sheet-qr-info',
  'sheet-fit-mode',
  'sheet-fit-hint',
  'sheet-columns',
  'sheet-rows',
  'sheet-margin',
  'sheet-gap',
  'sheet-offset-x',
  'sheet-offset-y',
  'sheet-info',
  'table-qr',
  'table-note',
  'label-profile',
  'profile-hint',
  'density',
  'copies',
  'show-title',
  'label-format',
  'label-text',
  'label-margin',
  'label-font',
  'label-cut',
  'export-labels',
  'printer-dot',
  'printer-name',
  'connect',
  'disconnect',
  'ble-support',
  'print-label',
  'print-status',
  'preview',
  'print',
  'print-root',
  'toast',
]);
